Fake deprecated nova client properties
Mox doesn't like the new nova client python properties that
were recently added to handle deprecations; just fake them out.

- UnknownMethodCallError: Method called is not a member of the object:
projectid

Change-Id: Iea69ee5c4a8f40eadc15391938443b04116cb3c3